package com.djcao.boot.repository;
// Generated 2019-7-3 7:08:02 by Hibernate Tools 5.2.8.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="sneakerlover"
)
public class User  implements java.io.Serializable {


     private Long id;
     private Date createTime;
     private Date updateTime;
     private String outerId;
     private String userName;
     private String passwd;
     private Byte isVip;
     private String ext;
     private String email;
     private Integer phoneNum;

    public User() {
    }

    public User(Date createTime, Date updateTime, String outerId, String userName, String passwd, Byte isVip, String ext, String email, Integer phoneNum) {
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.outerId = outerId;
       this.userName = userName;
       this.passwd = passwd;
       this.isVip = isVip;
       this.ext = ext;
       this.email = email;
       this.phoneNum = phoneNum;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_time", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
    @Column(name="outer_id", length=80)
    public String getOuterId() {
        return this.outerId;
    }
    
    public void setOuterId(String outerId) {
        this.outerId = outerId;
    }

    
    @Column(name="user_name", length=80)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="passwd")
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    
    @Column(name="is_vip")
    public Byte getIsVip() {
        return this.isVip;
    }
    
    public void setIsVip(Byte isVip) {
        this.isVip = isVip;
    }

    
    @Column(name="ext")
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_num")
    public Integer getPhoneNum() {
        return this.phoneNum;
    }
    
    public void setPhoneNum(Integer phoneNum) {
        this.phoneNum = phoneNum;
    }




}


